#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'EndeavourOS - AMD Radeon Graphics' {
    load_video
    set gfxpayload=keep
    insmod gzio
    insmod part_gpt
    insmod btrfs
    search --no-floppy --fs-uuid --set=root 0228c5f1-0b81-4039-8f1f-7cb61d3999c4
    echo 'EndeavourOS mit AMD Radeon Graphics wird geladen'
    linux /@/boot/vmlinuz-linux root=UUID=0228c5f1-0b81-4039-8f1f-7cb61d3999c4 rw rootflags=subvol=@ nowatchdog nvme_load=YES loglevel=3 amd_iommu=on radeon.modeset=1
    echo 'Initiale Ramdisk wird geladen ...'
    initrd /@/boot/initramfs-linux.img
}

menuentry 'EndeavourOS - NVIDIA RTX 4060Ti Graphics' {
    load_video
    set_gfxpayload=keep
    insmod gzio
    insmod part_gpt
    insmod btrfs
    search --no-floppy --fs-uuid --set=root 0228c5f1-0b81-4039-8f1f-7cb61d3999c4
    echo 'EndeavourOS mit RTX 4060 Ti wird geladen'
    linux /@/boot/vmlinuz-linux root=UUID=0228c5f1-0b81-4039-8f1f-7cb61d3999c4 rw rootflags=subvol=@ nowatchdog nvme_load=YES loglevel=3 amd_iommu=on nvidia_drm.modeset=1
    echo 'Initiale Ramdisk wird geladen ...'
    initrd /@/boot/initramfs-linux.img
}

menuentry 'Manjaro - Custom Eintrag' {
    load_video
    set_gfxpayload=keep
    insmod gzio
    insmod part_gpt
    insmod btrfs
    search --no-floppy --fs-uuid --set=root 8d4358e8-35e4-40ef-90a7-bcbaf9dd72d5
    echo 'Manjaro wird geladet xD...'
    linux /@/boot/vmlinuz-6.9-x86_64 root=UUID=8d4358e8-35e4-40ef-90a7-bcbaf9dd72d5 rw rootflags=subvol=@ nowatchdog nvme_load=YES loglevel=3 amd_iommu=on
    echo 'initramfs wird geladen...'
    initrd /@/boot/initramfs-6.9-x86_64.img
}

menuentry 'Windows Boot Manager (on /dev/nvme0n1p1)' --class windows --class os $menuentry_id_option 'osprober-efi-0285-C4B0' {
        insmod part_gpt
        insmod fat
        search --no-floppy --fs-uuid --set=root 0285-C4B0
        chainloader /efi/Microsoft/Boot/bootmgfw.efi
}


